conditions: v1
sudo: required
dist: xenial
language: node_js
node_js:
  - '12'

addons:
  chrome: stable

services:
  - xvfb
cache:
  directories:
    - node_modules

before_install:
  - export DISPLAY=:99.0
  - chmod +x ./scripts/travis.sh

script: ./scripts/travis.sh

stages:
  - Tests
  - Release

jobs:
  fast_finish: true
  include:
    # https://docs.travis-ci.com/user/build-stages/deploy-github-releases/
    - stage: Release
      name: 'Releasing a new version'
      env: TRAVIS_MODE=release
      if: tag IS present
      deploy:
        - provider: releases
          api_key: $GH_TOKEN
          file_glob: true
          file: _dist/*.zip
          skip_cleanup: true
          on:
            tags: true
    # Required tests
    - stage: Tests
      if: ((branch = master) OR (tag IS present) OR (type = pull_request)) AND commit_message !~ /^chore\(release\)/
      name: 'Running build'
      env: TRAVIS_MODE=build
